name: Automated E2E Testing

on:
    pull_request:
    workflow_dispatch:

jobs:
    run-e2e-tests:
        name: Run E2E Tests
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the repository
            - name: Checkout under $GITHUB_WORKSPACE
              uses: actions/checkout@v2

            # Step 2: Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.x"

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm ci

            # Step 4: Run Cypress tests with Electron
            - name: Run Cypress Tests with Electron
              uses: cypress-io/github-action@v4
              with:
                  browser: electron
              env:
                  API_BASE_URL: ${{ secrets.API_BASE_URL }}
                  userEmail: ${{ secrets.USER_EMAIL }}
                  userPassword: ${{ secrets.USER_PASSWORD }}
