name: Automated Unit Testing
on:
    pull_request:
    workflow_dispatch:

jobs:
    run-unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run test-unit
              env:
                  TEST_USER_EMAIL: ${{ secrets.JEST_USER_EMAIL }}
                  TEST_USER_PASSWORD: ${{ secrets.JEST_USER_PASSWORD }}
                  API_BASE_URL: ${{ secrets.API_BASE_URL }}
